---
title: "Logistic regression"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(glmulti)
library(broom)
library(modelr)
library(pROC)
```

```{r}
juice_data <- read_csv("data/orange_juice.csv") %>% 
  clean_names

head(juice_data)
```

```{r}
summary(juice_data)
```
```{r}
juice_data %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
```


```{r}
juice_wrangled <- juice_data %>% 
  mutate(
    purchase_mm = as_factor(ifelse(purchase == "MM", "y", "n")),
    store_id = as_factor(store_id),
    special_ch = as_factor(special_ch),
    special_mm = as_factor(special_mm),
    store7 = as_factor(store7),
    store = as_factor(store)
  ) %>% 
  select(-c("purchase", "weekof_purchase"))
```

```{r}

alias(purchase_mm ~ ., data = juice_wrangled)
```

```{r}
juice_wrangled <- juice_wrangled %>% 
  select(-c("sale_price_mm", "sale_price_ch", "price_diff", "store7"))
```

```{r}
#Create training & test data
n_data <- nrow(juice_wrangled)
test_index <- sample(1:n_data, size = n_data * 0.2)

test  <- slice(juice_wrangled, test_index)
train <- slice(juice_wrangled, -test_index)

```

```{r}
#Set up glmulti
glmulti_search_all_mains <- glmulti(
  purchase_mm ~ ., 
  data = train,
  level = 1,               # No interactions considered, main effects only
  method = "h",            # Exhaustive approach
  crit = "bic",            # BIC as criteria
  confsetsize = 10,        # Keep 10 best models
  plotty = F, 
  report = F,              # No plots, but provide interim reports
  fitfunction = "glm",     # glm function
  family = binomial(link = "logit")) # binomial family for logistic regression
```


```{r}
summary(glmulti_search_all_mains)
```
```{r}
juice_facs_with_mod1 <- juice_wrangled %>% 
  add_predictions(glmulti_search_all_mains, type = "response")
```


```{r}
roc_obj_mod1 <- glmulti_search_all_mains %>% 
  roc(response = purchase_mm, predictor = pred)
```
 


```{r}
glmulti_search_previous_mains_one_pair <- glmulti(
  purchase_mm ~ disc_mm + loyal_ch + pct_disc_ch + list_price_diff,
  data = train,
  level = 2,               # Interactions considered
  method = "h",            # Exhaustive approach
  crit = "bic",            # BIC as criteria
  confsetsize = 10,        # Keep 10 best models
  marginality = TRUE,      # consider pairs only if both main effects in model
  minsize = 6,             # minsize, maxsize and marginality here force 
  maxsize = 6,             # inclusion of a single pair beyond the five main effects
  plotty = F, 
  report = F,              # No plots, but provide interim reports
  fitfunction = "glm",     # glm function
  family = binomial(link = "logit")) # binomial family for logistic regression

```

```{r}
summary(glmulti_search_previous_mains_one_pair)
```

```{r}
roc_curve <- ggroc(
  data = list(
  no_interactions = glmulti_search_all_mains),
  pair_interactions = glmulti_search_previous_mains_one_pair,
                   legacy.axes = TRUE) +
  coord_fixed()

roc_curve
```

