---
title: "R Notebook - investigating data"
output: html_notebook
---

This notebook contains the R code for the exploratory data analysis/visualisation of the 'game_sales' dataset. It will be used for design/build of the Shiny app.


```{r}
library(tidyverse)
library(CodeClanData)
library(skimr)
```

```{r}
game_sales <- game_sales

skim(game_sales)

```


----------------------------------------------
Summary tables for dashboard front page
----------------------------------------------

```{r}
#Top titles

game_sales %>% 
  filter(year_of_release != 1988) %>% 
  select(name, genre, year_of_release, platform,critic_score, user_score, sales) %>% 
  slice_max(sales, n = 10)
  

```


```{r}
#Top titles by critic score

game_sales %>% 
  distinct(name, .keep_all = TRUE) %>% 
  select(name, year_of_release, platform, critic_score) %>% 
  slice_max(critic_score, n = 10)
```

```{r}
#Top 10 user rated
game_sales %>% 
  distinct(name, .keep_all = TRUE) %>% 
  select(name, year_of_release, platform, user_score) %>% 
  slice_max(user_score, n = 10)
```

```{r}
# top selling genres
game_sales %>% 
  select(genre, sales) %>% 
  group_by(genre) %>% 
  summarise(total_sales = sum(sales)) %>% 
  slice_max(total_sales, n = 10)
```

-------------------------------------------
Tables for top 10 analysis page
-------------------------------------------

```{r}
game_sales %>% 
  select(name,
         genre,
         year_of_release,
         platform,
         critic_score,
         user_score,
         sales) %>% 
  #filter(year_of_release == 2008) %>% 
  #filter(platform = USER CHOICE)
  #filter(genre = USER CHOICE)
  slice_max(critic_score, n = 10)
  #user choice on what slice_max will be based on: sales, critic_score or user_score
```

--------------------------------
Tables for second analysis tab - by year
-----------------------------

```{r}
game_sales %>% 
  filter(year_of_release != 1988) %>% 
  group_by(year_of_release) %>% 
  summarise(total_sales = sum(sales),
            average_critic_score = mean(critic_score),
            average_user_score = mean(user_score))
```


```{r}
#ALL YEARS SALES
game_sales %>% 
  filter(year_of_release != 1988) %>% 
  ggplot() +
  aes(x = year_of_release,
      y = sales) +
  geom_col()
  
```

```{r}
#ALL YEARS AVERAGE RATING
game_sales %>% 
  filter(year_of_release != 1988) %>% 
  group_by(year_of_release) %>% 
  summarise(average_critic = mean(critic_score)) %>% 
  ggplot() +
  aes(x = year_of_release,
      y = average_critic) %>% 
  geom_col()

```

---------------------------------------
Tables for third tab - analyis by platform
---------------------------------------

```{r}
game_sales %>% 
  filter(year_of_release != 1988) %>% 
  filter(platform %in% c("Wii", "PS2")) %>% 
  ggplot() +
  aes(x = year_of_release,
      y = sales,
      fill = platform) +
  geom_col() +
  facet_wrap(~ platform)
  

```

```{r}
game_sales %>% 
  filter(year_of_release != 1988) %>% 
  filter(platform %in% c("Wii", "PS2")) %>%
  group_by(platform, year_of_release) %>% 
  summarise(total_sales = sum(sales))
```

```{r}
game_sales %>% 
  ggplot() +
  aes(x = year_of_release, y = critic_score) +
  geom_point(alpha = 0.2)
```

