---
title: "Week6 Day2 Homework"
output: html_notebook
---


```{r}
# Load Libraries
library(tidyverse)
library(janitor)
library(skimr)
```

Q1
```{r}
# Read data
mobiles <- read_csv("data/20190928-items.csv")

skim(mobiles)
```

Q2 - Brand with highest number of phones: Samsung
```{r}
mobiles %>%
  group_by(brand) %>%
  summarise(count = n()) %>%
  slice_max(count, n = 5)
```

Q3
```{r}
samsung <- mobiles %>%
  filter(brand == "Samsung") %>%
  select(rating) 

samsung_stats <- samsung %>% 
  summarise(
    mean = mean(rating),
    sd = sd(rating)
  )
```


```{r}
samsung %>%
  ggplot() +
  aes(x = rating) +
  geom_histogram(
    aes(y = ..density..),
    col = "white",
    bins = 40
  ) +
stat_function(
    fun = dnorm,
    args = list(
      mean = samsung_stats$mean,
      sd = samsung_stats$sd
    ),
    col = "red"
  )
```

Q4
```{r}
# Within one SD of mean

samsung %>% 
  filter(rating >= samsung_stats$mean - samsung_stats$sd) %>% 
  filter(rating <= samsung_stats$mean + samsung_stats$sd) %>%
  summarise(prop_within_1sd = n()/nrow(samsung))


```
```{r}
#Within 2 SDs of mean

samsung %>% 
  filter(rating >= samsung_stats$mean - (2 * samsung_stats$sd))%>% 
  filter(rating <= samsung_stats$mean + (2 * samsung_stats$sd)) %>%
  summarise(prop_within_2sd = n()/nrow(samsung))
```
```{r}
#Within 3 SDs of mean

samsung %>% 
  filter(rating >= samsung_stats$mean - (3 * samsung_stats$sd))%>% 
  filter(rating <= samsung_stats$mean + (3 * samsung_stats$sd)) %>%
  summarise(prop_within_3sd = n()/nrow(samsung))
```

If a variable is normally distributed then expect 68%, 95% and 99.7% of observations within +/- 1, 2, 3 sd from the mean.
For the phone ratings distribution we see 79%, 92% and 98% of observations within +/- 1, 2, 3 sd from the mean.